### ISSUE TITLE
Approximation tolerance does not work

### ISSUE THREAD

**Issue by thomaskole** [PadLex/SvgToGcode#14]
The readme hints at a `TOLERANCES['approximation'] ` variable to tweak the output detail of the gcode.
It doesn't seem to work, I'm getting the exact same output no matter the setting.
My test SVG is about A4 in size (mm), and I'm getting multiple steps per mm of travel.

Thanks in advance

**Comment by PadLex** [comment]
Interesting, could you attach the problematic SVG file?

**Comment by thomaskole** [comment]
I'm a bit embarrassed. 
The one SVG I decide to test happens to be very complex, with many, many points. I'll attach it.

After simplifying the shape, I had better luck.

I think it would be interesting if the software handled subdivided edges as well.
I tried a single edge subdivided into many small segments, and it put out many points, rather than just two.

[test.svg.zip](https://github.com/PadLex/SvgToGcode/files/6510860/test.svg.zip)
