### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isnumeric'

### ISSUE THREAD

**Issue by EvansPM** [PadLex/SvgToGcode#15]
Certain svg throw this error:
```
AttributeError: 'NoneType' object has no attribute 'isnumeric'
```
Is there some specification required for the input svg?
My svg(path only) was created with potrace.

**Comment by PadLex** [comment]
It shouldn't do that. Could you share the troublesome SVG?

**Comment by EvansPM** [comment]
To try you can remove height attribute of your example svg.
Actually i fixe it and make pull request for it [fc31c77 ](https://github.com/EvansPM/SvgToGcode/commit/fc31c77e3f18d5072b8db527dfc793799986d8ce).
This worry about only the **height**, if you do not use **width** anywhere...
My svg from potrace got attribute *viewBox* only probably because i use [Potracer](https://pypi.org/project/potracer/) instead of [Potrace](http://potrace.sourceforge.net/).

**Comment by PadLex** [comment]
I merged your pull request. Thanks again!
